### PR TITLE
Setup TravisCI

### PR DESCRIPTION
**Pull request by lumie31**
This pull request fixes `issue #15`. Had to make some modifications to the test scripts to make tests pass with available data

### CODE REVIEW

**Comment by obahareth** [comment]
Thank you so much @lumie31, I'm traveling at the moment, I'll take a look at this in the coming days!

**Comment by lumie31** [comment]
> Thank you so much @lumie31, I'm traveling at the moment, I'll take a look at this in the coming days!

Alright. Enjoy the trip

**Comment by EhsanZ** [comment]
Hi @lumie31, thanks for your work, but I think you shouldn't comment out the failing tests, if that will make the build fails then it should fail. 

Regards.

**Comment by lumie31** [comment]
> Hi @lumie31, thanks for your work, but I think you shouldn't comment out the failing tests, if that will make the build fails then it should fail.
> 
> Regards.

Oh, I think you're right. A failing build makes one know that work still has to be done. Will look into this now.

**Review by obahareth — CHANGES_REQUESTED** [review]
Hey @lumie31, thanks a lot for the awesome work!

Could you please make the Tailwind changes in their own PR, and keep this just for setting up TravisCI?

Could you also uncomment the failing tests? I'll fix them. It should work once I add Arabic versions of each conference/meetup and IDs.

**Comment by lumie31** [comment]
Hello @obahareth, I actually didn't want all the PR's to be together like the way it currently is. 

How do I delete the PR's that aren't related to the Travis CI setup? Don't seem to know how to do that. 

Currently finding out ways to do so, just wanted to post this so I won't spend too much time researching what isn't a big deal

**Comment by obahareth** [comment]
Hey @lumie31, I think one way to do it would be to make a new branch on your fork with its starting point as master from my repo. Then you could [cherry-pick](https://www.previousnext.com.au/blog/intro-cherry-picking-git) the commits related to TravisCI from your old branch into your new branch. You could then make a new PR using the new branch.

**Comment by lumie31** [comment]
Thanks for the info @obahareth. Couldn't make much headway with the method you suggested above so I resulted to fixing each issue in its own branch, that way there won't be any clash of PR's like I had before

**Comment by lumie31** [comment]
Hello, I wanted to ask if I could close this PR since I already worked on the issues on different branches?

**Comment by obahareth** [comment]
Yeah @lumie31, I'll go ahead and close this one out for yeah.

**Pull request closed without merging**
