### PR TITLE
Tailwindcss-dir Setup

### PR DESCRIPTION
**Pull request by lumie31**
This PR attempts to fix `issue #16`

### CODE REVIEW

**Review by obahareth — CHANGES_REQUESTED** [review]
Hey @lumie31, this PR still has some changes from the Travis PR, could you merge my master branch into your branch so the conflicts get resolved?

Also the tests are already failing on master, I'll get that fixed, you don't need to have them commented out here.

**Comment by obahareth** [comment]
Also @lumie31 I take it this is just adding and setting up the RTL plugin, but I would still have to go and apply it to places where RTL styling is messed up still, right?

**Comment by lumie31** [comment]
Hello, @obahareth I seem to have resolved every issue with this PR over here. Is there anything that needs to be done on this PR before it's closed?

And concerning the RTL plugin -- Yes, It should be applied to places where the RTL styling is still messed up.

**Comment by obahareth** [comment]
Hey @lumie31, you still have changes to a spec file where you commented out a number of tests.

**Comment by lumie31** [comment]
Hello @obahareth, so sorry about this. I have uncommented the tests in the spec file. Hope this fixes the issue now. I'm really sorry for making this PR drag.

**Comment by lumie31** [comment]
> Hello @obahareth, so sorry about this. I have uncommented the tests in the spec file. Hope this fixes the issue now. I'm really sorry for making this PR drag.

I seem to have run into some clutter with git over here and I'm encountering some difficulties. Wanted to know if everything is okay at your end and if this PR can be closed.

**Review by obahareth — APPROVED** [review]

**Comment by obahareth** [comment]
It's completely alright @lumie31, it happens to all of us :). If you'd ever like some help in dealing with Git, I'd be happy to help you out. I personally use [GitKraken](https://www.gitkraken.com/) and it helps me out a lot. 

Thanks for your contribution and your continued help in this repo.

**Comment by lumie31** [comment]
So glad this has been approved. On to the next one. Would look into what "GitKraken" offers. Thank you so much!

**Pull request merged**
